apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ai-service
    version: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-blue
  labels:
    app: ai-service
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-service
      version: blue
  template:
    metadata:
      labels:
        app: ai-service
        version: blue
    spec:
      containers:
      - name: ai-service
        image: woragis/ai-service:v1.1.0
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-green
  labels:
    app: ai-service
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-service
      version: green
  template:
    metadata:
      labels:
        app: ai-service
        version: green
    spec:
      containers:
      - name: ai-service
        image: woragis/ai-service:v1.2.0
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# To switch from blue to green:
# kubectl patch service ai-service -p '{"spec":{"selector":{"version":"green"}}}'
# To rollback:
# kubectl patch service ai-service -p '{"spec":{"selector":{"version":"blue"}}}'

